In [10]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Columns of Tables are Arrays ##

In [11]:
nba = Table.read_table('nba_salaries.csv').relabeled(4, 'SALARY')
warriors = nba.where('team', 'Golden State Warriors')

In [12]:
warriors

rank | name              | position | team                  | SALARY  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [13]:
salary_select = warriors.select('SALARY')
salary_select

SALARY
5250000
4988000
4200000
4200000
3937000
2600000
2503000
5611000
4800000
4800000
... (301 rows omitted)

In [14]:
type(salary_select)
# Returns a column in a table format

datascience.tables.Table

In [15]:
salary_col = warriors.column('SALARY')
salary_col

array([ 5250000,  4988000,  4200000,  4200000,  3937000,  2600000,
        2503000,  5611000,  4800000,  4800000,  4386000,  3578000,
        3390000,  2678000,  1842000,   757000,   316000,   316000,
         241000,    32000,  6235000,  5400000,  5400000,  4913000,
        4441000,  4400000,  3388000,  3000000,  2343000,  2021000,
        1310000,   333000,   333000,  6858000,  6000000,  5540000,
        4935000,  4469000,  4400000,  1409000,   700000,   512000,
       10912000,  7482000,  5445000,  4400000,  1667000,  1507000,
        3000000,  2481000,  2390000,  2232000, 13700000,  8888888,
        7365079,  7312500,  5393300,  4506261,  1988160,  1910520,
        1857360,  1760000,  1404360,   448762,   423762, 15070000,
        9999999,  8125000,  2535260,  2157097,  2061720,  1986960,
         798112,   744551,   664209,   259770, 16440000,  8425625,
        6630000,  4000000,  3470771,  3000000,  2636696,  2323080,
        2216400,  1800000,  1345800,   770610,   770610,   687456,
         358107,   251272, 11000000,  9000000,  8275862,  7140000,
        4500000,  2900000,  2497320,  1709280,  1634000,  1446720,
        1262520,   797581,   711517,   711517,   442114,   442114,
         442114,   422725, 11000000,  9000000,  8937931,  4140000,
        3100000,  2710560,  1837560,  1600000,  1000497,   855189,
         825497,   825497,   736420,   632455,   118435,    17328,
       11000000, 10800000,  9000000,  6883800,  4447792,  3540000,
        3065040,  2913840,  2225000,  1254720,   855189,   854389,
         825497,   825497,   762195,   762195,   473604,   133723,
       11610000,  9000000,  6750000,  4099920,  3823000,  3117120,
        2956658,  2126520,  1027424,   855189,   854389,   854389,
         854389,   825497,   785487,   650000,   633253,   473604,
         473604,   211084,    75793, 13000000, 12744000, 10164000,
        9000000,  5400000,  4099920,  4000000,  4000000,  3958742,
        2798040,  2222160,  1020960,   884293,   854389,   854389,
         854389,   850000,   825497,   762195,   633253,   473604,
         211084,    75793, 14000000, 13878000, 12868632,  9887642,
        3500000,  2923920,  2317920,  2162419,  2000000,  1056720,
         875500,   660619,   490180, 15012000, 12972973, 12289544,
       10629213,  5305000,  3657500,  3075880,  3049920,  1145685,
        1145685,  1112880,  1104240,   915243,   915243,   816482,
         816482,   816482,   167122, 15501000, 14260870, 13800000,
       11710456, 11370786,  5543725,  3873398,  3815000,  2500000,
        2008748,  1270964,  1131960,   947276,   947276,   845059,
         289755, 26540100, 16663575, 15330435, 12112359, 11131368,
        5782450,  2898000,  1403611,  1182840,  1171560,   980431,
         980431,   980431,   980431,   980431,   980431,   980431,
         543471,   543471,   543471,   543471,   543471, 37457154,
       17826150, 17469565, 14814815,  7692308,  5192000,  3477600,
        1544951,  1471382,  1471382,  1471382,  1471382,  1378242,
        1312611,  1312611,  1312611,  1312611,   980431,   980431,
         980431,   980431,   815615,   543471,   543471,   543471,
         543471, 37457154, 30000000, 18988725, 17469565, 16000000,
        8307692,  5337000,  1644240,  1544951,  1544951,  1512601,
        1512601,  1378242,  1349383,   307648, 40231758, 32742000,
       18539130,  4464226,  2177483,  1964760,  1897800,   898310,
         898310,   842327,   654469,   350189,   350189])

In [16]:
type(salary_col)

numpy.ndarray

In [ ]:
#np.average(salary_select)
# can't call numpy function on tables

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U6'), dtype('<U6'), dtype('<U12'))

In [18]:
np.average(salary_col)

4315935.9228295824

## Practice

Find the total salary paid to Chicago Bulls players in the year 2010.
- Use where to narrow the table to the right team and year.
- Use column to extract the correct column as an array.
- Use the sum command on the array.

In [25]:
bulls = nba.where('team', 'Chicago Bulls')
bulls2010 = bulls.where('season', 2010)
#bulls2010.show()
salary_arr = bulls2010.column('SALARY')
np.average(salary_arr)

3476431.9411764704